name: Test and release gcfg.v1
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/v1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: tatskaari/release-action@master
        with:
          release-files: .
